// <auto-generated />
using System;
using BabySphere.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BabySphere.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260811101903_changes")]
    partial class changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BabySphere.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@babysphere.com",
                            Password = "admin123"
                        });
                });

            modelBuilder.Entity("BabySphere.Models.BabyProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BabyProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Travel",
                            Description = "Comfortable stroller for outdoor travel.",
                            ImageUrl = "/images/stroller.jpg",
                            Name = "Baby Stroller",
                            Price = 149.99m,
                            Quantity = 15,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 2,
                            Category = "Travel",
                            Description = "Safe and secure car seat for babies.",
                            ImageUrl = "/images/carseat.jpg",
                            Name = "Baby Car Seat",
                            Price = 199.99m,
                            Quantity = 10,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Category = "Travel",
                            Description = "Spacious diaper bag for parents.",
                            ImageUrl = "/images/diaperbag.jpg",
                            Name = "Diaper Bag",
                            Price = 39.99m,
                            Quantity = 19,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 4,
                            Category = "Feeding",
                            Description = "BPA-free feeding bottle.",
                            ImageUrl = "/images/bottle.jpg",
                            Name = "Baby Bottle",
                            Price = 12.99m,
                            Quantity = 15,
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 5,
                            Category = "Feeding",
                            Description = "Comfortable feeding chair for babies.",
                            ImageUrl = "/images/highchair.jpg",
                            Name = "High Chair",
                            Price = 89.99m,
                            Quantity = 8,
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 6,
                            Category = "Feeding",
                            Description = "Soft bibs to keep clothes clean.",
                            ImageUrl = "/images/bibs.jpg",
                            Name = "Baby Bibs",
                            Price = 9.99m,
                            Quantity = 23,
                            Rating = 3.7999999999999998
                        },
                        new
                        {
                            Id = 7,
                            Category = "Care",
                            Description = "Gentle lotion for baby skin.",
                            ImageUrl = "/images/lotion.jpg",
                            Name = "Baby Lotion",
                            Price = 8.99m,
                            Quantity = 12,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 8,
                            Category = "Care",
                            Description = "Tear-free shampoo for babies.",
                            ImageUrl = "/images/shampoo.jpg",
                            Name = "Baby Shampoo",
                            Price = 7.99m,
                            Quantity = 17,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 9,
                            Category = "Care",
                            Description = "Soft and comfortable diapers.",
                            ImageUrl = "/images/diapers.jpg",
                            Name = "Diapers Pack",
                            Price = 24.99m,
                            Quantity = 20,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 10,
                            Category = "Toys",
                            Description = "Educational blocks for learning.",
                            ImageUrl = "/images/blocks.jpg",
                            Name = "Building Blocks",
                            Price = 19.99m,
                            Quantity = 23,
                            Rating = 3.7000000000000002
                        },
                        new
                        {
                            Id = 11,
                            Category = "Toys",
                            Description = "Soft plush teddy bear.",
                            ImageUrl = "/images/teddy.jpg",
                            Name = "Teddy Bear",
                            Price = 14.99m,
                            Quantity = 27,
                            Rating = 3.6000000000000001
                        },
                        new
                        {
                            Id = 12,
                            Category = "Toys",
                            Description = "Colorful rattle toy for babies.",
                            ImageUrl = "/images/rattle.jpg",
                            Name = "Baby Rattle",
                            Price = 6.99m,
                            Quantity = 16,
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("BabySphere.Models.Babysitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Babysitters");
                });

            modelBuilder.Entity("BabySphere.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BabysitterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BabySphere.Models.ParentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CareNeeds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChildAge")
                        .HasColumnType("int");

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParentProfiles");
                });

            modelBuilder.Entity("BabySphere.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@babysphere.com",
                            FullName = "BabySphere Administrator",
                            Password = "admin123",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "parent@babysphere.com",
                            FullName = "Test Parent",
                            Password = "parent123",
                            Role = "Parent"
                        },
                        new
                        {
                            Id = 3,
                            Email = "babysitter@babysphere.com",
                            FullName = "Test Babysitter",
                            Password = "babysitter123",
                            Role = "Babysitter"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
